### ISSUE TITLE
[event list item] reveal additional information on click

### ISSUE THREAD

**Issue by afknapping** [Kriesse/wwwtf.berlin#1]
- codepen: http://codepen.io/filtercake/pen/mJYJaL

**Comment by fredericmarx** [comment]
I really like the idea!

There's probably 100 ways to do this. I did another implementation, that I also quite like for several reasons:
- Listitems open on tab focus
- Listitems in open state all have their own URL (wwwtf.berlin#event1 etc)
- Probably a person with better a11y skills should look into this but I think this might also do better in that respect

Downsides:
- Doesn't work in browsers without :target-support (http://caniuse.com/#feat=css-sel3) but we could feature detect and just give them expanded listitems by default if they don't have it

Codepen: http://codepen.io/fmarx/pen/PqvZNZ

**Comment by afknapping** [comment]
@fredericmarx so much +1 for all of this, go go go! :) will close #3

**Comment by fredericmarx** [comment]
I pushed a version of the CSS thing.

Hope everything worked out, still learning how to Github

**Comment by sareg0** [comment]
I'm pretty sure it did. I can see it on my end
