### ISSUE TITLE
[event list item] Rainbow color gradient effect

### ISSUE THREAD

**Issue by fredericmarx** [Kriesse/wwwtf.berlin#5]
It would be awesome if we could make that happen.

Maybe @filtercake can help with some Sassy color wheel magic :)

![clear-1 1-for-ios-iphone-screenshot](https://cloud.githubusercontent.com/assets/954294/9307701/54240128-4500-11e5-8b28-c32671796f8a.jpg)

**Comment by afknapping** [comment]
http://sassmeister.com/gist/548324ba2a69e40b0c36

notes to self:
- n color shades
- get lighten() max value in % so text is still readable
- max-lighten / n to get %-delta per step for lighten and darken
- loop through n lighten() steps, i <= n, lighten(i \* %-delta)
- [Controlling color with Sass color functions](https://robots.thoughtbot.com/controlling-color-with-sass-color-functions)
- [Aesthetic Sass 2: Colors and Palettes | Scotch](https://scotch.io/tutorials/aesthetic-sass-2-colors)
- [Colors - A nicer color palette for the web.](http://clrs.cc/)

**Comment by afknapping** [comment]
@fredericmarx do you really mean rainbow or just shades of a basecolor? i can probably come up with sth for the latter. rainbow would work too, but is more difficult because contrast changes and interference with text color...

**Comment by fredericmarx** [comment]
Sorry, "rainbow" was misleading. I would probably do a gradient with 2 colors. If we use `lighten` the text could become unreadable at some point.

Also, maybe there's a way to do it with a script that's aware of the number of list items (JS or Jekyll)? With Sass we would have to do a speculative number of `:nth-child()` and hope there will never be more items than rules.

**Comment by sareg0** [comment]
@fredericmarx like this? http://output.jsbin.com/galabu

**Comment by fredericmarx** [comment]
Thanks @sareg0, that was super helpful! :) I built a solution based on your JS. 🌈🎉💫
